languageCode = "zh-cn"
languageName = "cn"
displayName = "ğŸ‡¨ğŸ‡³"
isoCode = "zh-cn"
weight = 1
rtl = false

title = "è±†é€—å­çš„å°é»‘å±‹"
# logo = "img/logo.png"
description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2006-01-02"

[author]
  name = "Weaxsey"
  image = "img/blowfish_logo.png"
  headline = ""
  bio = ""
   links = [
     { email = "459312872@qq.com" },
     { github = "https://github.com/Weaxs" },
     { steam = "https://steamcommunity.com/id/weaxs" },
     { weibo = "https://weibo.com/u/5462117754" },
   ]
