languageCode = "zh-cn"
languageName = "cn"
displayName = "ğŸ‡¨ğŸ‡³"
isoCode = "zh-cn"
weight = 1
rtl = false

title = "è±†é€—å­çš„å°é»‘å±‹"
logo = "img/FF7cc.png"
description = "æ¬¢è¿æ¥åˆ°è±†é€—å­çš„å°é»‘å±‹"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2006-01-02"

[author]
  name = "Weaxs"
  image = "img/Satoru Gojo.jpeg"
  headline = ""
  bio = ""
  links = [
    { email = "/links/email" },
    { github = "https://github.com/Weaxs" },
    { steam = "https://steamcommunity.com/id/weaxs" },
  ]
