languageCode = "zh-cn"
languageName = "cn"
weight = 1
title = "è±†é€—å­çš„å°é»‘å±‹"

[params]
  displayName = "ğŸ‡¨ğŸ‡³"
  isoCode = "zh-cn"
  description = "æ¬¢è¿æ¥åˆ°è±†é€—å­çš„å°é»‘å±‹"
  dateFormat = "2006-01-02"
  rtl = false
  logo = "img/FF7cc.png"
  copyright = "Â©{ year } [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh-hans)"

[author]
  name = "Weaxs"
  image = "img/Satoru Gojo.jpeg"
  headline = ""
  bio = ""
  links = [
    { email = "/links/email" },
    { github = "https://github.com/Weaxs" },
    { steam = "https://steamcommunity.com/id/weaxs" },
    { nintendo-switch = "/links/nintendo-switch" },
  ]
